### ISSUE TITLE
Erro on install v8

### ISSUE THREAD

**Issue by LiberTang0** [projectexpert/pmis#18]
I have this error in log when i install it on new database:

2017-05-19 09:16:08,897 6425 ERROR pmis8 openerp.sql_db: bad query: ALTER TABLE "account_analytic_account" ALTER COLUMN "active_analytic_planning_version" SET NOT NULL
Traceback (most recent call last):
  File "/odoo-8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "active_analytic_planning_version" contains null values

2017-05-19 09:16:08,898 6425 WARNING pmis8 openerp.models: WARNING: unable to set column active_analytic_planning_version of table account_analytic_account not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE account_analytic_account ALTER COLUMN active_analytic_planning_version SET NOT NULL
Traceback (most recent call last):
  File "/odoo-8/openerp/models.py", line 2666, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, k))
  File "/odoo-8/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo-8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "active_analytic_planning_version" contains null values

**Comment by LiberTang0** [comment]
And these warning message on install too:

2017-05-19 09:16:18,061 6425 INFO pmis8 openerp.modules.module: module analytic_billing_plan: creating or updating database tables
2017-05-19 09:16:18,907 6425 INFO pmis8 openerp.modules.loading: loading analytic_billing_plan/wizard/analytic_billing_plan_line_make_sale.xml
2017-05-19 09:16:18,932 6425 WARNING pmis8 openerp.models: ir.values.create() with unknown fields: object

2017-05-19 09:16:27,082 6425 INFO pmis8 openerp.modules.loading: loading analytic_resource_plan_purchase_request/wizard/analytic_resource_plan_line_make_purchase_request.xml
2017-05-19 09:16:27,118 6425 WARNING pmis8 openerp.models: ir.values.create() with unknown fields: object

2017-05-19 09:16:46,013 6425 INFO pmis8 openerp.modules.loading: loading project_time_milestone/project_time_milestone_view.xml
2017-05-19 09:16:46,129 6425 WARNING pmis8 openerp.models: ir.actions.act_window.create() with unknown fields: inherit_id

**Comment by sysadminmatmoz** [comment]
1. Set the Active Plan Version in the analytic.account form for the existing projects and set the  default value in the Analytic Planning Versions (accounting/configuration/analytic accounting/analytic planning version - chose the default one and check the boolean box on it for default planning version).
2. Set the default for resource in the planning version
